# Use an official Node runtime as a parent image
FROM node:14

# Ownership commands need to be after user creation.
# Set the working directory in the container
WORKDIR /usr/src/app

# Switch to non-root user
USER node

# Make port 8080 available to the world outside this container
EXPOSE 8080
