"""empty message

Revision ID: 02eab6a4b85b
Revises: 8639605fb3f8
Create Date: 2019-01-10 15:29:13.436932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eab6a4b85b'
down_revision = '8639605fb3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tracker_projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracker_projects', type_='foreignkey')
    op.drop_column('tracker_projects', 'user_id')
    # ### end Alembic commands ###
