"""empty message

Revision ID: 6d4534801245
Revises: 9ef67415dda2
Create Date: 2019-01-11 11:34:56.002517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4534801245'
down_revision = '9ef67415dda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tracker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'trackers', ['tracker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'tracker_id')
    # ### end Alembic commands ###
