"""empty message

Revision ID: 3afca4f6422c
Revises: 2bef46a531d4
Create Date: 2022-10-05 17:31:35.827079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afca4f6422c'
down_revision = '2bef46a531d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_trackers_upload',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'tracker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_trackers_upload')
    # ### end Alembic commands ###
