"""empty message

Revision ID: 580ca512482d
Revises: 7d45a8d3efb4
Create Date: 2019-01-11 09:10:24.036210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '580ca512482d'
down_revision = '7d45a8d3efb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('tracker_id', sa.Integer(), nullable=True))
    op.drop_constraint('categories_ibfk_1', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'trackers', ['tracker_id'], ['id'])
    op.drop_column('categories', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_ibfk_1', 'categories', 'projects', ['project_id'], ['id'])
    op.drop_column('categories', 'tracker_id')
    # ### end Alembic commands ###
