"""empty message

Revision ID: 7d45a8d3efb4
Revises: 44a23a423986
Create Date: 2019-01-11 09:05:19.465084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d45a8d3efb4'
down_revision = '44a23a423986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'last_updated')
    op.drop_column('activities', 'deleted')
    op.drop_column('tracker_projects', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_projects', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    op.add_column('activities', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('last_updated', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
