"""empty message

Revision ID: a05b0f3d301f
Revises: 580ca512482d
Create Date: 2019-01-11 09:16:41.916661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b0f3d301f'
down_revision = '580ca512482d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('last_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'last_sync')
    # ### end Alembic commands ###
