"""empty message

Revision ID: c4c32fd44fc9
Revises: c7ce4da4ea78
Create Date: 2019-01-10 14:25:18.669822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4c32fd44fc9'
down_revision = 'c7ce4da4ea78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('uploaded', sa.Boolean(), nullable=True))
    op.drop_column('activities', 'external_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('activities', 'uploaded')
    # ### end Alembic commands ###
