"""empty message

Revision ID: c7ce4da4ea78
Revises: 3db118b90e22
Create Date: 2019-01-09 10:37:38.685869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ce4da4ea78'
down_revision = '3db118b90e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('external_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'external_id')
    # ### end Alembic commands ###
