"""empty message

Revision ID: e6406dfd09ac
Revises: 829c3bebae96
Create Date: 2019-01-10 18:05:21.993623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6406dfd09ac'
down_revision = '829c3bebae96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_projects', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_constraint('tracker_projects_ibfk_3', 'tracker_projects', type_='foreignkey')
    op.create_foreign_key(None, 'tracker_projects', 'users', ['userid'], ['id'])
    op.drop_column('tracker_projects', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_projects', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracker_projects', type_='foreignkey')
    op.create_foreign_key('tracker_projects_ibfk_3', 'tracker_projects', 'users', ['user_id'], ['id'])
    op.drop_column('tracker_projects', 'userid')
    # ### end Alembic commands ###
